OFERTAS_MOCK = [
    {
        "id": 1,
        "nombre": "Playa Rincón, Samaná",
        "descripcion_corta": "Una de las playas más vírgenes del Caribe. Agua cristalina, palmeras y paz total.",
        "descripcion_general": "Playa Rincón es considerada una de las diez playas más hermosas del mundo. Ubicada en la península de Samaná, es un paraíso sin urbanización: no hay hoteles en la orilla, solo naturaleza pura. Llegarás en lancha desde Las Galeras y te recibirá una playa de más de 3 km de arena blanca rodeada de palmeras. Sin música de resort, sin sombrillas de plástico — solo el sonido del mar y una brisa perfecta. Es el plan ideal para los que de verdad quieren desconectarse.",
        "imagen_url": "/playa_rincon.jpg",
        "imagen_secundaria": "/playa_rincon2.jpg",   # segunda foto para la sección de descripción
        "precio": 4500,
        "duracion": "1 día completo",
        "hospedaje": "No incluido (day trip)",
        "transporte": "Lancha incluida",
        "comidas": "Almuerzo de pescado incluido",
        "incluye": [
            "Transporte ida y vuelta en lancha",
            "Almuerzo de pescado fresco en la playa",
            "Guía local",
            "Equipo de snorkel",
        ],
        "no_incluye": [
            "Bebidas adicionales",
            "Propinas",
            "Gastos personales",
        ],
        "itinerario": [
            "07:00 AM — Salida desde Santo Domingo hacia Samaná",
            "10:30 AM — Llegada a Las Galeras, abordamos la lancha",
            "11:00 AM — Llegada a Playa Rincón",
            "11:00 AM - 01:00 PM — Tiempo libre, snorkel y baño",
            "01:00 PM — Almuerzo de pescado fresco en la playa",
            "03:00 PM — Tiempo libre para explorar la playa",
            "03:30 PM — Regreso en lancha a Las Galeras",
            "07:00 PM — Llegada aproximada a Santo Domingo",
        ],
    },
    {
        "id": 2,
        "nombre": "Laguna Dudú, Río San Juan",
        "descripcion_corta": "Lagunas azul turquesa rodeadas de palmeras. El spot más instagrameable del norte.",
        "descripcion_general": "La Laguna Dudú es un sistema de lagunas naturales de aguas azul intenso ubicadas en Cabrera, norte de la República Dominicana. El agua tiene ese tono turquesa irreal que solo ves en fotos — pero es completamente real. Puedes tirarte en tirolesa sobre el agua, nadar en la laguna subterránea iluminada por rayos de sol, o simplemente flotar en sus aguas cálidas. El lugar también incluye una cueva con murciélagos y un río subterráneo que pocos turistas conocen.",
        "imagen_url": "/laguna_dudu.jpg",
        "imagen_secundaria": "/laguna_dudu2.jpg",
        "precio": 3800,
        "duracion": "1 día completo",
        "hospedaje": "No incluido",
        "transporte": "Autobús incluido desde SD",
        "comidas": "Snacks incluidos",
        "incluye": [
            "Transporte ida y vuelta en autobús",
            "Entrada a las lagunas",
            "Tirolesa incluida",
            "Snacks y agua",
            "Guía local",
        ],
        "no_incluye": [
            "Almuerzo (hay restaurantes en el área)",
            "Propinas",
            "Fotografías profesionales",
        ],
        "itinerario": [
            "06:30 AM — Salida desde Santo Domingo",
            "10:00 AM — Llegada a Laguna Dudú",
            "10:15 AM — Tirolesa y saltos al agua",
            "12:00 PM — Exploración de la cueva subterránea",
            "01:30 PM — Almuerzo libre en restaurantes del área",
            "03:00 PM — Tiempo libre para nadar y explorar",
            "04:30 PM — Salida de regreso",
            "08:00 PM — Llegada aproximada a Santo Domingo",
        ],
    },
    {
        "id": 3,
        "nombre": "Isla Saona, La Romana",
        "descripcion_corta": "La postal perfecta del Caribe: arenas blancas, aguas turquesas y cócteles en el agua.",
        "descripcion_general": "Isla Saona forma parte del Parque Nacional del Este y es la excursión más icónica de República Dominicana — y con razón. La isla tiene ese aspecto de postal caribeña que parece editado pero no lo es: arena blanca finísima, agua en varios tonos de azul y turquesa, y palmeras inclinadas sobre el mar. El tour incluye parada en una piscina natural donde caminas literalmente sobre el agua (solo 1 metro de profundidad) rodeado de estrellas de mar. El regreso es en catamarán con música, open bar y mucho ambiente.",
        "imagen_url": "/isla_saona.jpg",
        "imagen_secundaria": "/isla_saona2.jpg",
        "precio": 6200,
        "duracion": "1 día completo",
        "hospedaje": "No incluido",
        "transporte": "Catamarán y lancha incluidos",
        "comidas": "Almuerzo buffet y open bar incluidos",
        "incluye": [
            "Transporte en lancha rápida de ida",
            "Regreso en catamarán con open bar",
            "Parada en piscina natural con estrellas de mar",
            "Almuerzo buffet en la playa",
            "Equipo de snorkel",
        ],
        "no_incluye": [
            "Bebidas fuera del open bar",
            "Propinas",
            "Fotos profesionales",
        ],
        "itinerario": [
            "08:00 AM — Salida en lancha desde Bayahibe",
            "09:30 AM — Parada en la piscina natural (estrellas de mar)",
            "11:00 AM — Llegada a Isla Saona, tiempo libre en la playa",
            "01:00 PM — Almuerzo buffet frente al mar",
            "02:30 PM — Tiempo libre para explorar la isla",
            "03:00 PM — Abordamos el catamarán para regresar",
            "05:30 PM — Llegada a Bayahibe con música y open bar",
        ],
    },
    {
        "id": 4,
        "nombre": "27 Charcos de Damajagua",
        "descripcion_corta": "Adrenalina pura: salta entre cascadas naturales en el corazón de Puerto Plata.",
        "descripcion_general": "Las 27 Charcos de Damajagua son un sistema de cascadas naturales de roca caliza color dorado ubicadas a 20 minutos de Puerto Plata. La actividad consiste en subir caminando por la selva tropical y luego bajar saltando, deslizándote y nadando por los charcos naturales formados por el río. El agua es fría y el paisaje es impresionante — paredes de roca dorada, árboles tropicales y cascadas que caen de varios metros. Puedes elegir el recorrido de 7, 12 o 27 charcos según tu nivel de aventura y energía.",
        "imagen_url": "/damajagua.jpg",
        "imagen_secundaria": "/damajagua2.jpg",
        "precio": 5100,
        "duracion": "1 día completo",
        "hospedaje": "No incluido",
        "transporte": "Autobús incluido desde Puerto Plata",
        "comidas": "No incluidas",
        "incluye": [
            "Transporte desde Puerto Plata",
            "Entrada y guía certificado",
            "Casco y chaleco salvavidas",
            "Opción de 7, 12 o 27 charcos",
        ],
        "no_incluye": [
            "Alimentación",
            "Propinas",
            "Zapatos de agua (se pueden alquilar en el lugar)",
        ],
        "itinerario": [
            "08:30 AM — Encuentro en Puerto Plata",
            "09:30 AM — Llegada a Damajagua, briefing de seguridad",
            "10:00 AM — Caminata por la selva hacia los charcos",
            "10:45 AM — Inicio del recorrido (eliges 7, 12 o 27 charcos)",
            "01:30 PM — Fin del recorrido, tiempo para descansar",
            "02:30 PM — Almuerzo libre en el área",
            "04:00 PM — Regreso a Puerto Plata",
        ],
    },
]
 